## Experiment No 8
## Tools for EDA-Study of numpy library
## Name:Atharva Jadhav
## PRN:25070123027
## Batch: ENTC A2

In [ ]:
# Why NumPy?
# Faster than lists
# Used for numerical computation
# Base for Pandas

In [ ]:
# Declaration of NumPy
import numpy as np
a=np.array([10,20,30,40])
b=np.array([[1,2,3],[9,8,7]])## 2 square brackects are required
print(a)
print(b)

[10 20 30 40]
[[1 2 3]
 [9 8 7]]


## In built functions in NumPy

In [ ]:
# To check dimenstions
print(a.ndim)
print(b.ndim)

1
2


In [ ]:
# Shape of A & B
print(a.shape)
print(b.shape)

(4,)
(2, 3)


In [ ]:
# To check the DataType
print(a.dtype)
print(b.dtype)

int64
int64


In [ ]:
# To use np as zeros
np.zeros((1,3))

array([[0., 0., 0.]])

In [ ]:
# To use np as ones
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# To use np as eye (Diagonal Matrix)
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# To use np as arranging (Print 1 to 12 with spacing 3)
np.arange(1,12,3)

array([ 1,  4,  7, 10])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
c=a*2
d=a+5
print(c)
print(d)

[20 40 60 80]
[15 25 35 45]


In [ ]:
a+5

array([15, 25, 35, 45])

In [ ]:
# To use np as mean
np.mean(a)

np.float64(25.0)

In [ ]:
# To use np as median
np.median(a)

np.float64(25.0)

In [ ]:
# To use np as maximum
np.max(a)

np.int64(40)

In [ ]:
# To use np as minimum
np.min(a)

np.int64(10)

In [ ]:
# To use np as sum
np.sum(a)

np.int64(100)